### ISSUE TITLE
`xmake project -k cmake` Does not generate a proper Cmake file for MacOS

### ISSUE THREAD

**Issue by Frityet** [xmake-io/xmake#1633]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
After creating a new XMake project, I tried to generate a CMake file so I could use CLion as my main IDE, which threw an exception

### Expected behavior
I expected a valid CMake file for use with CLion

### Error output

```yaml
Cannot get compiler information:
	Compiler exited with error code 1: /Library/Developer/CommandLineTools/usr/bin/cc -xc -g -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk -mmacosx-version-min=10.15 -arch -DNDEBUG -O3 -fpch-preprocess -v -dD -E
	Apple clang version 12.0.0 (clang-1200.0.32.29)
	Target: unknown-apple-darwin19.6.0
	Thread model: posix
	InstalledDir: /Library/Developer/CommandLineTools/usr/bin
	clang: error: invalid arch name '-arch -DNDEBUG'
```

> If it is a xmake related compilation problem, please add the `-v -D` parameter and give the detailed compilation output information.

### Related Environment

Please provide compiling and running environment information:

- xmake version: v2.5.7+202108290309
- os: MacOS Catalina (10.15.7)
- target platform: MacOS/Windows
