### ISSUE TITLE
global 'platform' is not callable (a nil value)

### ISSUE THREAD

**Issue by samayala22** [xmake-io/xmake#3448]
### Xmake Version

2.7.7

### Operating System Version and Architecture

Ubuntu

### Describe Bug

After setting up a linux build workflow on github, i keep getting the following error when configurating my build:

```bash
error: ./.xmake-cache-W09/share/xmake/core/base/interpreter.lua:16[7](https://github.com/AER8875-2022/AeroFLEX/actions/runs/4317475206/jobs/7534582985#step:9:8)9: ...make-cache-W09/share/xmake/platforms/appletvos/xmake.lua:21: global 'platform' is not callable (a nil value)
stack traceback:
    [...make-cache-W09/share/xmake/platforms/appletvos/xmake.lua:21]: in main chunk

stack traceback:
    [C]: in function 'error'
    [./.xmake-cache-W09/share/xmake/core/base/os.lua:912]:
    [./.xmake-cache-W09/share/xmake/core/base/interpreter.lua:1679]:
    [./xmake.lua:11]: in main chunk

checking for platform ... linux
checking for architecture ... x[8](https://github.com/AER8875-2022/AeroFLEX/actions/runs/4317475206/jobs/7534582985#step:9:9)6_64
error: ./.xmake-cache-W0[9](https://github.com/AER8875-2022/AeroFLEX/actions/runs/4317475206/jobs/7534582985#step:9:10)/share/xmake/core/base/interpreter.lua:1679: ...make-cache-W09/share/xmake/platforms/appletvos/xmake.lua:21: global 'platform' is not callable (a nil value)
stack traceback:
    [...make-cache-W09/share/xmake/platforms/appletvos/xmake.lua:21]: in main chunk

stack traceback:
    [C]: in function 'error'
    [./.xmake-cache-W09/share/xmake/core/base/os.lua:912]:
    [./.xmake-cache-W09/share/xmake/core/base/interpreter.lua:1679]:
    [./xmake.lua:[11](https://github.com/AER8875-2022/AeroFLEX/actions/runs/4317475206/jobs/7534582985#step:9:12)]: in main chunk
```
I don't understand why it's calling something for the appletvos platform. 

From https://github.com/AER8875-2022/AeroFLEX/actions/runs/4316976036/jobs/7533454528

### Expected Behavior

Expected to configure without issues just like the windows build.

### Project Configuration

See https://github.com/AER8875-2022/AeroFLEX/blob/main/xmake.lua

Workflow file:

```yaml
name: linux-build
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: ["--toolchain=gcc"]

    steps:
      - uses: actions/checkout@v3

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: ".xmake-cache"

      - name: Config
        run: |
          xmake f -y -a x64 -m release ${{ matrix.compiler }}
      - name: Build
        run: |
          xmake -vD
```

Multiple versions of this workflow file were tried.
