### ISSUE TITLE
Unable to build xmake on MacOS 13.4 x86_64

### ISSUE THREAD

**Issue by Frityet** [xmake-io/xmake#4181]
### Xmake Version

2.8.1

### Operating System Version and Architecture

macOS Ventura 13.4

### Describe Bug

I am unable to compile or install (through the official install script `curl -fsSL https://xmake.io/shget.text | bash`). I get linker errors

### Expected Behavior

Xmake builds and installs

### Project Configuration

nil

### Additional Information and Error Logs

```yaml
compiling.release core/src/demo/xmake.c
linking.release build/xmake
ld: archive has no table of contents file 'build/macosx/x86_64/release/liblua_cjson.a'
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
gmake: *** [makefile:2602: build/xmake] Error 1
make failed!
```
