### ISSUE TITLE
在github action上，传递给cmake参数中，错误使用v144不存在的工具链

### ISSUE THREAD

**Issue by 1143910315** [xmake-io/xmake#5204]
### Xmake 版本

xmake v2.9.2+HEAD.6b6557c54

### 操作系统版本和架构

Microsoft Windows Server 2022   10.0.20348

### 描述问题

![error](https://github.com/xmake-io/xmake/assets/20817444/6b354401-9eac-4120-a917-f3fe7007e7dc)

github action错误日志信息
本地编译正常

### 期待的结果

github action编译成功

### 工程配置

===================xmake.lua

```lua
add_rules("mode.debug", "mode.release", "mode.releasedbg")

add_repositories("liteldev-repo https://github.com/LiteLDev/xmake-repo.git")
add_requires("levilamina v0.12.4","icu4c","cpp-httplib") -- or add_requires("levilamina x.x.x") to specify target LeviLamina version

if not has_config("vs_runtime") then
    set_runtimes("MD")
end

target("FeiluluWorld") -- Change this to your plugin name.
    add_cxflags(
        "/EHa",
        "/utf-8"
    )
    add_files(
        "src/**.cpp"
    )
    add_includedirs(
        "src"
    )
    add_packages(
        "levilamina",
        "icu4c",
        "cpp-httplib"
    )
    add_shflags(
        "/DELAYLOAD:bedrock_server.dll" -- Magic to import symbols from BDS
    )
    set_exceptions("none") -- To avoid conflicts with /EHa
    set_kind("shared")
    set_languages("cxx23")

    after_build(function (target)
        local plugin_packer = import("scripts.after_build")

        local plugin_define = {
            pluginName = target:name(),
            pluginFile = path.filename(target:targetfile()),
        }
        
        plugin_packer.pack_plugin(target,plugin_define)
    end)
```
===================build.yml====github action
```
on:
  pull_request:
  push:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: xmake-io/github-action-setup-xmake@v1
      
      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m release -p windows -v -y

      - run: |
          xmake -y

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-windows-x64-${{ github.sha }}
          path: |
            bin/
```

### 附加信息和错误日志

无
