### ISSUE TITLE
macosx下mingw使用cmake找不到windres

### ISSUE THREAD

**Issue by Biobots** [xmake-io/xmake#948]
### 描述问题

macosx下mingw使用cmake找不到windres

### 期待的结果

macosx-mingw-cmake可以正常使用windres

### 错误信息

``` 
windres -O coff -DGLEW_BUILD -DGLEW_NO_GLU -Dglew_EXPORTS -I/Users/runner/.xmake/cache/packages/2009/g/glew/2.1.0/source/glew-2.1.0/build/cmake/../../include   /Users/runner/.xmake/cache/packages/2009/g/glew/2.1.0/source/glew-2.1.0/build/glew.rc CMakeFiles/glew.dir/Users/runner/.xmake/cache/packages/2009/g/glew/2.1.0/source/glew-2.1.0/build/glew.rc.obj make[2]: windres: No such file or directory
 ```

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：dev分支
- xmake运行平台：CI-macosx-mingw
- xmake目标平台：windows

### 其他信息

尝试了如下修改：

https://github.com/Biobots/xmake/commit/94c985cd329909c51682d3572a6630a7b56bc882

但是本地没有macosx环境，不知是否可行。另外`github-action-setup-xmake`是否可以指定使用非官方仓库便于测试？

**Comment by waruqi** [comment]
之前没传进去，这么改应该可以 ci上有macos环境，你可以fork后 在自己的ci上测试

> 另外github-action-setup-xmake是否可以指定使用非官方仓库便于测试？

xmake 的ci默认就是走的本地源码，你直接fork后自己跑的ci也就是用的你的那份代码

https://github.com/xmake-io/xmake/blob/092e4d20ec4e4a09d45525645fe8c8e8b0edbb58/.github/workflows/linux.yml#L22

**Comment by Biobots** [comment]
> xmake 的ci默认就是走的本地源码，你直接fork后自己跑的ci也就是用的你的那份代码

我指的是xmake-repo中的ci，因为我本地没有macos环境，需要在xmake-repo中的ci测试一下，而xmake-repo是调用了`github-action-setup-xmake`使用本仓库(xmake-io/xmake)的dev分支，这里的仓库能否改成我fork并修改后的仓库(xxxx/xmake)？

**Comment by waruqi** [comment]
是支持的，可以试试下面的方式指定自己的repo

xmake-version: xmake-io/xmake#dev

https://github.com/xmake-io/github-action-setup-xmake/blob/222091ba4ba9cc718346f0d064ea71d97b0b76b2/src/versions.ts#L117

不行就xmake repo下的ci弄个x
case一样可以测，或者自己xmake-repo 里面自己 git clone源码装下也可以

**Comment by Biobots** [comment]
参照这个versions.ts把mingw.yml修改如下：

```yaml
steps:
      - uses: actions/checkout@v1
      - name: clone
        run: git clone --recursive -b dev https://github.com/Biobots/xmake-repo.git xmakesrc
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: local#xmakesrc

      - name: prepare
        run: |
          brew install mingw-w64

      - name: tests
        run: |
          xmake l ./scripts/test.lua -vD -p mingw
```

编译报错log如下：
```shell
Run git clone --recursive -b dev https://github.com/Biobots/xmake-repo.git xmakesrc
Cloning into 'xmakesrc'...

Run xmake-io/github-action-setup-xmake@v1
Use local xmake at '/Users/runner/work/xmake-repo/xmake-repo/xmakesrc'
install local xmake at '/Users/runner/work/xmake-repo/xmake-repo/xmakesrc'
  /usr/bin/make build
  make: *** No rule to make target `build'.  Stop.
##[error]The process '/usr/bin/make' failed with exit code 2
```
